apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-module-28071
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-module-28071
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
